# Generated by Django 3.2.19 on 2023-06-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='clade',
            field=models.CharField(blank=True, max_length=100, verbose_name='family'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='birthday',
            field=models.DateField(verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='breed'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='chip_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='chip number'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
