# Generated by Django 3.2.19 on 2023-06-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20230616_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='clade',
            field=models.CharField(max_length=100, verbose_name='family'),
        ),
    ]
