# Generated by Django 3.2.19 on 2023-06-20 13:14

import django.db.models.deletion
from django.db import migrations, models

import pets.models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_clade'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default/no-image.jpg', upload_to=pets.models.pet_avatar_directory_path, verbose_name='image')),
            ],
            options={
                'verbose_name': 'pet avatar',
                'verbose_name_plural': 'pet avatars',
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='image_url',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pet', to='pets.petavatar'),
        ),
    ]
