# Generated by Django 3.2.19 on 2023-06-20 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20230620_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petavatar',
            name='image_url',
        ),
        migrations.AddField(
            model_name='petavatar',
            name='pet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avatar', to='pets.pet'),
        ),
    ]
