# Generated by Django 3.2.19 on 2023-06-20 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20230620_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petavatar',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='avatar', to='pets.pet'),
        ),
    ]
