# Generated by Django 3.2.19 on 2023-07-20 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_petavatar_pet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'pet', 'verbose_name_plural': 'pets'},
        ),
    ]
